CascadeBot/CascadeBot

src/main/java/com/cascadebot/cascadebot/CascadeBot.java

In alignment to Google's Code Style

Fix variable naming and order

---

README.md
src/main/java/com/cascadebot/cascadebot/CascadeBot.java
src/main/java/com/cascadebot/cascadebot/ShutdownHandler.java
src/main/java/com/cascadebot/cascadebot/commands/core/InviteCommand.java

Added InviteCommand.java, added a shutdown message using Logger and also changed the spacing in a comment in CascadeBot.java because it was really annoying me. Also added a README.md
We should add ;invite to the bot because it gives users a chance to invite the bot to their own server, and spread the love 'n good vibes.

Add ;invite and shutdown message (console) also add readme

---

PULL_REQUEST_TEMPLATE.md

If this is a new feature why should we add it to the bot.

I need to test this PR

---

config.example.yml
pom.xml
src/main/java/com/cascadebot/cascadebot/CascadeBot.java
src/main/java/com/cascadebot/cascadebot/data/Config.java
src/main/java/com/cascadebot/cascadebot/events/ButtonEventListener.java
src/main/resources/logback.xml
src/main/resources/sentry.properties

Add sentry to the bot for reporting errors

---

src/main/java/com/cascadebot/cascadebot/commandmeta/CommandType.java
src/main/java/com/cascadebot/cascadebot/commands/fun/CatCommand.java
src/main/java/com/cascadebot/cascadebot/commands/fun/DogCommand.java

cat and dog commands

---

src/main/java/com/cascadebot/cascadebot/commands/fun/DogCommand.java

Change "cat" to "dog" in a few instances

---

src/main/java/com/cascadebot/cascadebot/commands/core/SupportCommand.java

SupportCommand

---

src/main/java/com/cascadebot/cascadebot/commands/moderation/KickCommand.java
src/main/java/com/cascadebot/cascadebot/commands/moderation/SoftBanCommand.java

Not allow people to try to use Moderation commands on the bot and sender

👀 I don't think letting people do this is a good idea

---

src/main/java/com/cascadebot/cascadebot/commands/developer/DumpCommand.java
src/main/java/com/cascadebot/cascadebot/commands/developer/EvalCommand.java
src/main/java/com/cascadebot/cascadebot/commands/informational/RolesCommand.java
src/main/java/com/cascadebot/cascadebot/commands/informational/UserInfoCommand.java
src/main/java/com/cascadebot/cascadebot/events/CommandListener.java
src/main/java/com/cascadebot/cascadebot/messaging/Messaging.java
src/main/java/com/cascadebot/cascadebot/utils/FormatUtils.java
src/main/java/com/cascadebot/cascadebot/utils/PasteUtils.java
src/main/java/com/cascadebot/cascadebot/utils/Table.java
src/main/java/com/cascadebot/cascadebot/utils/pagination/PageObjects.java
src/main/java/com/cascadebot/cascadebot/utils/pagination/PageUtils.java

- Adding commands and permissions to the dump command
- Add a better pasteutils class to reduce repeated code

Dump command

---

src/main/java/com/cascadebot/cascadebot/commands/moderation/SoftBanCommand.java

Change permission ban to softban

---

src/main/java/com/cascadebot/cascadebot/commands/informational/UserInfoCommand.java
src/main/java/com/cascadebot/cascadebot/utils/DiscordUtils.java

Added the ability for user info to work for only users instead of a member of the guild.
Also added a `getUser` method to simplify getting users

Userinfo Command Improvements

---

pom.xml
src/main/java/com/cascadebot/cascadebot/CascadeBot.java
src/main/java/com/cascadebot/cascadebot/commandmeta/CommandContext.java
src/main/java/com/cascadebot/cascadebot/commands/informational/UserInfoCommand.java
src/main/java/com/cascadebot/cascadebot/commands/moderation/BanCommand.java
src/main/java/com/cascadebot/cascadebot/commands/moderation/KickCommand.java
src/main/java/com/cascadebot/cascadebot/commands/moderation/SoftBanCommand.java
src/main/java/com/cascadebot/cascadebot/commands/moderation/UnbanCommand.java
src/main/java/com/cascadebot/cascadebot/data/objects/GuildData.java
src/main/java/com/cascadebot/cascadebot/data/objects/GuildModeration.java
src/main/java/com/cascadebot/cascadebot/messaging/MessagingObjects.java
src/main/java/com/cascadebot/cascadebot/moderation/ModAction.java
src/main/java/com/cascadebot/cascadebot/moderation/ModerationManager.java
src/main/java/com/cascadebot/cascadebot/permissions/CascadePermission.java
src/main/java/com/cascadebot/cascadebot/utils/DiscordUtils.java
src/main/java/com/cascadebot/cascadebot/utils/buttons/ButtonGroup.java

Moderation manager

---

config.example.yml
src/main/java/com/cascadebot/cascadebot/data/Config.java
src/main/java/com/cascadebot/cascadebot/events/GeneralEvents.java

So I think we should have hello and goodbye messages that are sent when we are added/removed from a guild. This will allow us to include things like: 
- Links to our panel
- A removal survey
- Awareness on things people need to be aware of
- Etc etc

Add hi and goodbye

---

src/main/java/com/cascadebot/cascadebot/moderation/ModerationManager.java

Cannot do anything with guild owners

Moderation and guild owners

---

README.md
src/main/java/com/cascadebot/cascadebot/commands/moderation/BanCommand.java
src/main/java/com/cascadebot/cascadebot/moderation/ModAction.java
src/main/java/com/cascadebot/cascadebot/moderation/ModerationManager.java

Force banning users

---

src/main/java/org/cascadebot/cascadebot/ShutdownHandler.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/guild/GuildFlagSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/guild/GuildSaveSubCommand.java
src/main/java/org/cascadebot/cascadebot/data/managers/GuildDataManager.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildData.java
src/main/java/org/cascadebot/cascadebot/events/ButtonEventListener.java
src/main/java/org/cascadebot/cascadebot/events/CommandListener.java
src/main/java/org/cascadebot/cascadebot/events/GuildSaveListener.java
src/main/java/org/cascadebot/cascadebot/messaging/Messaging.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java
src/main/java/org/cascadebot/cascadebot/music/MusicHandler.java
src/main/java/org/cascadebot/cascadebot/utils/ConfirmUtils.java
src/main/java/org/cascadebot/cascadebot/utils/pagination/PageObjects.java

I think maybe keeping it in GuildData allows for more direct storage of the player
🤷‍♂️ let me know what you think

Suggestion: Move player storage into GuildData

---

src/main/java/org/cascadebot/cascadebot/commands/core/InviteCommand.java
src/main/java/org/cascadebot/cascadebot/commands/core/SupportCommand.java
src/main/java/org/cascadebot/cascadebot/commands/developer/DumpCommand.java
src/main/java/org/cascadebot/cascadebot/commands/developer/EvalCommand.java
src/main/java/org/cascadebot/cascadebot/commands/developer/GuildCommand.java
src/main/java/org/cascadebot/cascadebot/commands/developer/RestartCommand.java
src/main/java/org/cascadebot/cascadebot/commands/developer/ShutdownCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/CatCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/DogCommand.java
src/main/java/org/cascadebot/cascadebot/commands/informational/RolesCommand.java
src/main/java/org/cascadebot/cascadebot/commands/informational/ServerInfoCommand.java
src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java
src/main/java/org/cascadebot/cascadebot/commands/management/ModuleCommand.java
src/main/java/org/cascadebot/cascadebot/commands/moderation/BanCommand.java
src/main/java/org/cascadebot/cascadebot/commands/moderation/KickCommand.java
src/main/java/org/cascadebot/cascadebot/commands/moderation/SoftBanCommand.java
src/main/java/org/cascadebot/cascadebot/commands/moderation/UnbanCommand.java

Change command descriptions to make sense

---

src/main/java/org/cascadebot/cascadebot/events/PlayerListener.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java

As discussed I've moved `PlayerListener` into the `events` package with everything else and named `LoopType` to `LoopMode` as well as including more conventional getters and setters

Move PlayerListener

---

src/main/java/org/cascadebot/cascadebot/commands/music/PauseCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/ResumeCommand.java

Pause and Resume commands

---

src/main/java/org/cascadebot/cascadebot/commands/music/StopCommand.java

(Music) Stop Command

---

src/main/java/org/cascadebot/cascadebot/commands/music/SearchCommand.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingUI.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java
src/main/java/org/cascadebot/cascadebot/music/MusicHandler.java
src/main/java/org/cascadebot/cascadebot/utils/FormatUtils.java

Added a new UI messaging method for showing loaded tracks
Search command.

Search command

---

src/main/java/org/cascadebot/cascadebot/commands/music/PlayingCommand.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java
src/main/java/org/cascadebot/cascadebot/music/MusicHandler.java
src/main/java/org/cascadebot/cascadebot/utils/FormatUtils.java
src/main/java/org/cascadebot/cascadebot/utils/buttons/Button.java

Playing command

---

src/main/java/org/cascadebot/cascadebot/commands/music/VolumeCommand.java
src/main/java/org/cascadebot/cascadebot/events/CommandListener.java
src/main/java/org/cascadebot/cascadebot/permissions/PermissionsManager.java

Volume Command

---

src/main/java/org/cascadebot/cascadebot/commands/music/LoopCommand.java

Loop command

---

src/main/java/org/cascadebot/cascadebot/commands/music/ShuffleCommand.java

Shuffle Command

---

src/main/java/org/cascadebot/cascadebot/CascadeBot.java
src/main/java/org/cascadebot/cascadebot/UnicodeConstants.java
src/main/java/org/cascadebot/cascadebot/commandmeta/CommandContext.java
src/main/java/org/cascadebot/cascadebot/commandmeta/CommandManager.java
src/main/java/org/cascadebot/cascadebot/commands/music/PlayCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SearchCommand.java
src/main/java/org/cascadebot/cascadebot/events/PlayerListener.java
src/main/java/org/cascadebot/cascadebot/exceptions/DiscordPermissionException.java
src/main/java/org/cascadebot/cascadebot/messaging/Messaging.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingObjects.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingTyped.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingUI.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java
src/main/java/org/cascadebot/cascadebot/music/MusicHandler.java
src/main/java/org/cascadebot/cascadebot/utils/EventWaiter.java
src/main/java/org/cascadebot/cascadebot/utils/StringsUtil.java

- Command to add songs to the queue

Play Command

---

src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java

I added return types and consumers to saving and loading playlists so we can have better detection in commands and give users more options.

improve saving and loading of playlists

---

pom.xml
src/main/java/org/cascadebot/cascadebot/CascadeBot.java
src/main/java/org/cascadebot/cascadebot/MDCException.java
src/main/java/org/cascadebot/cascadebot/events/CommandListener.java
src/main/java/org/cascadebot/cascadebot/messaging/Messaging.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingTyped.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingUI.java
src/main/resources/logback.xml

- JSON Logging
- Toggle by environment of `--json-logging`

JSON Logging

---

src/main/java/org/cascadebot/cascadebot/commands/music/QueueCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SkipCommand.java
src/main/java/org/cascadebot/cascadebot/events/PlayerListener.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java

Queue Command

---

src/main/java/org/cascadebot/cascadebot/commands/management/TagCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/JoinCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/LeaveCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/LoopCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/PauseCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/PlayCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/PlayingCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/QueueCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/ResumeCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SearchCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/ShuffleCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SkipCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/StopCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/VolumeCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagCategorySubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagCreateSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagDeleteSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagEditSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagListSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagPlaceholdersSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagRawSubCommand.java
src/main/resources/lang/en-GB.json

Added lang for strings in tag commands and music descriptions.

Languify tag commands and music descriptions

---

config.example.yml
pom.xml
src/main/java/org/cascadebot/cascadebot/CascadeBot.java
src/main/java/org/cascadebot/cascadebot/data/Config.java
src/main/java/org/cascadebot/cascadebot/data/managers/GuildDataManager.java
src/main/java/org/cascadebot/cascadebot/events/ButtonEventListener.java
src/main/java/org/cascadebot/cascadebot/events/CommandListener.java
src/main/java/org/cascadebot/cascadebot/events/JDAEventMetricsListener.java
src/main/java/org/cascadebot/cascadebot/events/PlayerListener.java
src/main/java/org/cascadebot/cascadebot/messaging/Messaging.java
src/main/java/org/cascadebot/cascadebot/metrics/BotMetricsCollector.java
src/main/java/org/cascadebot/cascadebot/metrics/Metrics.java
src/main/resources/logback.xml

All the metrics for prometheus including:
- JDA entity count per shard and total
- Command submitted and executed count
- Command execution time
- Commands errored
- Buttons pressed
- Failed rest actions
and more :D

Add prometheus metrics

---

src/main/java/org/cascadebot/cascadebot/commandmeta/CommandContext.java
src/main/java/org/cascadebot/cascadebot/commands/core/PrefixCommand.java
src/main/java/org/cascadebot/cascadebot/commands/management/SettingsCommand.java
src/main/java/org/cascadebot/cascadebot/commands/management/TagCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/PauseCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/ResumeCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/module/ModuleDisableSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/module/ModuleEnableSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/module/ModuleListSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagCategorySubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagCreateSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagDeleteSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagEditSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagListSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/subcommands/tag/TagRawSubCommand.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildData.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildPermissions.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettings.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettingsCore.java
src/main/java/org/cascadebot/cascadebot/data/objects/Setting.java
src/main/java/org/cascadebot/cascadebot/data/objects/SettingsContainer.java
src/main/java/org/cascadebot/cascadebot/events/CommandListener.java

- See issue #109 
Todo:
- Make settings command work with the `@SettingsContainer` annotation for different modules

Settings annotation

---

src/main/java/org/cascadebot/cascadebot/commands/fun/RandomNumberCommand.java

better ifs and removed unused imports
- Nothing, except simplified if's and removing unused imports

Simplified RandomNumberCommand

---

src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java

- Added a check that shows off official roles applicable to an user
- Merely an addition, adds checks if user x. has a special role `Owner`, `Developer` etc.

Show off highest official role

---

config.example.yml
src/main/java/org/cascadebot/cascadebot/permissions/PermissionsManager.java

- Updated example config to include contributor security level
- Removed check for `.` in wildcard checker in isValidPermission

Update example config and wildcard checking

---

src/main/java/org/cascadebot/cascadebot/commands/informational/ServerInfoCommand.java
src/main/resources/lang/en-GB.json

Minor changes to guild command to reduce errors

Fix/guildinfo 

---

README.md
src/main/java/org/cascadebot/cascadebot/Constants.java

To make sure we can change it without changing every single link

Use the abstract discord URL

---

src/main/java/org/cascadebot/cascadebot/data/database/DatabaseManager.java
src/main/java/org/cascadebot/cascadebot/permissions/objects/Group.java

Everything needs a default constructor :P 

---

src/main/java/org/cascadebot/cascadebot/commands/moderation/BanCommand.java
src/main/java/org/cascadebot/cascadebot/utils/DiscordUtils.java

Changed ban command to catch errors when the user is not found

Catch error on user not found

---

src/main/java/org/cascadebot/cascadebot/commands/informational/UserInfoCommand.java
src/main/resources/lang/en-GB.json

Show requester
Use InfoMessage colour
~~Use embed for roles~~
~~Add pages for when people have a lot of roles~~

Better use of embeds on userinfo

---

src/main/java/org/cascadebot/cascadebot/utils/Table.java
src/main/java/org/cascadebot/cascadebot/utils/pagination/PageUtils.java

What was i thinking when i made this

I'm a derp

---

pom.xml
src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionCommand.java
src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionDeleteSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/management/permission/UserPermissionTestSubCommand.java
src/main/resources/arguments.json
src/main/resources/lang/en-GB.json

- Fix a language issue with `;userperms test <user> <perm>`
- Add a command to delete a group (Woops)

Hotfix for v1.1

---

src/main/java/org/cascadebot/cascadebot/commands/core/HelpCommand.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildData.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettingsCore.java
src/main/java/org/cascadebot/cascadebot/utils/pagination/PageUtils.java
src/main/resources/lang/en-GB.json

- Adds a help menu so people can actually see what commands we have!

Help command

---

src/main/java/org/cascadebot/cascadebot/UnicodeConstants.java
src/main/java/org/cascadebot/cascadebot/commandmeta/Module.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoAddSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoAddUserSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoCreateSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoRemoveSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoRemoveUserSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoSendSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/useful/TodoViewSubCommand.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildData.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettingUseful.java
src/main/java/org/cascadebot/cascadebot/data/objects/GuildSettingsUseful.java
src/main/java/org/cascadebot/cascadebot/data/objects/TodoList.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingUI.java
src/main/java/org/cascadebot/cascadebot/utils/DiscordUtils.java
src/main/java/org/cascadebot/cascadebot/utils/buttons/ButtonGroup.java
src/main/resources/arguments.json
src/main/resources/lang/en-GB.json

Added Useful module
Added GuildSettingsUseful for said useful module
Added TodoList and TodoList Item objects for managing todo lists
New todo list command so you can set up all the things to do
Closes #153

Todo-list command

---

src/main/java/org/cascadebot/cascadebot/commands/fun/ColorCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/RandomChoiceSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/RandomColorSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/RandomCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/RandomNumberCommand.java
src/main/java/org/cascadebot/cascadebot/utils/ColorUtils.java
src/main/java/org/cascadebot/cascadebot/utils/PurgeUtils.java
src/main/java/org/cascadebot/cascadebot/utils/RandomUtils.java
src/main/resources/arguments.json
src/main/resources/lang/en-GB.json

- `;random color/choice`
- Fix for PurgeUtils (`smh`)
- Brand-new ColorUtils
- Fixed star imports in ColorCommand (smh)
- Because it's fun!

RandomCommand - Extension

---

src/main/java/org/cascadebot/cascadebot/commands/music/SeekCommand.java
src/main/resources/lang/en-GB.json

Added a check for livestreams as seek does not work with them

Seek improvements

---

README.md
src/main/java/org/cascadebot/cascadebot/commands/fun/CatCommand.java
src/main/java/org/cascadebot/cascadebot/commands/fun/DogCommand.java
src/main/java/org/cascadebot/cascadebot/commands/management/permission/GroupPermissionListSubCommand.java
src/main/java/org/cascadebot/cascadebot/commands/moderation/BanCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/LeaveCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SearchCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SeekCommand.java
src/main/java/org/cascadebot/cascadebot/commands/music/SkipCommand.java
src/main/java/org/cascadebot/cascadebot/messaging/MessagingUI.java
src/main/java/org/cascadebot/cascadebot/utils/DiscordUtils.java
src/main/java/org/cascadebot/cascadebot/utils/ParserUtils.java
src/main/java/org/cascadebot/cascadebot/utils/PermissionCommandUtils.java
src/main/resources/lang/en-GB.json

As listed in my section of #189

UI and UX Enhancements

---

src/main/java/org/cascadebot/cascadebot/commands/core/DonateCommand.java
src/main/resources/lang/en-GB.json

Donate Command

---

pom.xml
src/main/java/org/cascadebot/cascadebot/scripting/objects/ScriptGuild.java
src/main/java/org/cascadebot/cascadebot/scripting/objects/ScriptUser.java

Filled out all methods in ScriptGuild for CUSTOM SCRIPTING :tada:
Fix broken jcenter import (thanks @binaryoverload)

ScriptGuild Methods

---

src/main/java/org/cascadebot/cascadebot/commandmeta/ArgumentManager.java
src/main/java/org/cascadebot/cascadebot/commands/moderation/PurgeUserSubCommand.java
src/main/java/org/cascadebot/cascadebot/data/managers/PlaylistManager.java
src/main/java/org/cascadebot/cascadebot/permissions/CascadePermission.java
src/main/java/org/cascadebot/cascadebot/utils/PurgeUtils.java
src/main/resources/arguments.json
src/main/resources/lang/en-GB.json

Title sorta says it all!
- Fix playlist not working
- Change vararg to varargs
- Add full stops
That is all

Random Fixes

---

pom.xml

Bump the music versions in an effort to fix some issues. No idea if this will.

Bump the music versions

---

src/main/java/org/cascadebot/cascadebot/utils/pagination/PageCache.java
src/main/kotlin/org/cascadebot/cascadebot/commands/core/PageCommand.kt
src/main/kotlin/org/cascadebot/cascadebot/events/GuildEvents.kt
src/main/kotlin/org/cascadebot/cascadebot/messaging/Messaging.kt
src/main/resources/arguments.json
src/main/resources/lang/en-GB.json
src/test/kotlin/org/cascadebot/cascadebot/utils/WeightedListTest.kt

- A simple `;page` command that jumps to a page on the latest paged message

📄 Page Command

---

src/main/java/org/cascadebot/cascadebot/music/CascadeLavalinkPlayer.java
src/main/java/org/cascadebot/cascadebot/music/CascadeLavaplayerPlayer.java
src/main/java/org/cascadebot/cascadebot/music/CascadePlayer.java

The variables in an interface were static which caused a race condition

Move CascadePlayer to an Abstract class

---

src/main/kotlin/org/cascadebot/cascadebot/commands/management/SettingsListSubCommand.kt

Removed the ugly settings table and replaced with a nicely formatted list w/ emotes

Beautify settings list

---

src/main/java/org/cascadebot/cascadebot/music/CascadeLavalinkPlayer.java

Destroyed the lavalink connection so @mrjvs stops complaining about it rejoining

Destroy link instead of disconnecting

---

src/main/java/org/cascadebot/cascadebot/commands/informational/RolesCommand.java
src/main/java/org/cascadebot/cascadebot/utils/pagination/PageUtils.java

- Fixed roles command, preventing it to go passed 2000 characters

Hotfix: roles command
